version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: db-test
      MONGO_USERNAME: test
      MONGO_PASSWORD: test
    volumes:
      - ./script/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./script/mongo-data-init.sh:/docker-entrypoint-initdb.d/mongo-data-init.sh
    ports:
      - "27017:27017"
    command:
      - --auth